//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyealLibrary.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblActions
    {
        public int Id { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<byte> PersonalId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual TblBooks TblBooks { get; set; }
        public virtual TblMembers TblMembers { get; set; }
        public virtual TblPersonals TblPersonals { get; set; }
    }
}
