//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyealLibrary.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBooks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblBooks()
        {
            this.TblActions = new HashSet<TblActions>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<byte> CategoryId { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string Year { get; set; }
        public string Publisher { get; set; }
        public Nullable<int> Page { get; set; }
        public Nullable<bool> Situtation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblActions> TblActions { get; set; }
        public virtual TblAuthors TblAuthors { get; set; }
        public virtual TblCategories TblCategories { get; set; }
    }
}
